name: Test, Build, and Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: turing
          POSTGRES_PASSWORD: turing
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.1.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check server
        run: npm run typecheck -w=server

      - name: Type check client
        run: npm run typecheck -w=client

      - name: Lint server
        run: npm run lint -w=server

      - name: Lint client
        run: npm run lint -w=client

      - name: Test client (unit)
        run: npm run test -w=client

      - name: Test server (unit)
        run: npm run test -w=server
